apiVersion: v1
kind: Service
metadata:
  name: flask-todo-service
spec:
  type: NodePort
  selector:
    app: flask-todo
  ports:
    - port: 5000       # Port your container listens to
      targetPort: 5000 # Port your pod exposes
      nodePort: 30007  # External port on your machine (must be between 30000–32767)
